### ISSUE TITLE
Stacktrace on all Commands

### ISSUE THREAD

**Issue by psych0d0g** [cvarelaruiz/owi2plex#30]
Getting the following stacktrace on every command:
```
$ owi2plex  -h 192.168.0.172 -l
Traceback (most recent call last):
  File "/home/cronix/.local/bin/owi2plex", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/cronix/.local/bin/owi2plex.py", line 437, in main
    bouquets = getBouquets(bouquet=bouquet, api_root_url=api_root_url,
  File "/home/cronix/.local/bin/owi2plex.py", line 66, in getBouquets
    bouquets = bouquets_data.json()['bouquets']
  File "/home/cronix/.local/lib/python3.8/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

```

Running serverside: Ubuntu 20.04 LTS
VUUltimo using openvix with OWIF 1.4.5

**Comment by psych0d0g** [comment]
error found: server is on a diffrent subnet from the enigma box, i had to enable authentication for the webinterface, or add the option to also allow acces via VPN

**Comment by RubbeeDuck** [comment]
Hi @psych0d0g,

I have the same issue, What you have done exactely?

Thanks for help

Regards
